platform :ios, '12.2'

target 'NewsApp' do
  use_frameworks!

  # Pods for NewsApp
  pod 'RealmSwift', '~> 3.14'
  pod 'RxSwift', '~> 4.5'
  pod 'RxCocoa', '~> 4.5'

  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
