platform :ios, '12.2'

target 'NewsApp' do
  use_frameworks!

  # Pods for NewsApp
  pod 'Alamofire', '5.0.0-beta.5'

  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
