platform :ios, '12.2'

def shared_pods
  use_frameworks!

  pod 'RealmSwift', '~> 3.14'
  pod 'RxSwift', '~> 4.5'
  pod 'RxCocoa', '~> 4.5'
end

target 'BBCNewsApp' do
  shared_pods
end

target 'CBSNewsApp' do
  shared_pods
end

target 'BBCNewsAppTests' do
  shared_pods
  pod 'Nimble', '~>8.0'
  pod 'Quick', '~>2.1'
  pod 'OHHTTPStubs/Swift', '~>8.0'
end
